services:
  intersystems:
    image: intersystemsdc/iris-community:latest
    container_name: iris-comm
    ports:
      - "1972:1972"
      - "52773:52773"
    env_file:
    - path: ./app.env
      required: true

  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: streamlit_app
    depends_on:
      - intersystems
    ports:
      - "8501:8501"
      - "8502:8502"
    env_file:
    - path: ./app.env
      required: true
